### ISSUE TITLE
Support building images from in-memory Dockerfiles using fileobj

### ISSUE THREAD

**Issue by alexpdp7** [Jc2k/pytest-docker-tools#13]
Hi,

I'm trying to do something like:

```
import io

import pytest_docker_tools as pdt

dockerfile = io.BytesIO(b"""
FROM whatever
RUN xxx
""")

image = pdt.build(fileobj=dockerfile)
container = pdt.image(image='{image.id}')
```

, but I'm getting all kinds of errors, because I think `build` and `image` are confused by not having `path`, `name`.

I think using `fileobj` is not supported, but it would be pretty cool. I can work around this in several ways, but I'm wondering if this could be supported relatively easily. I could try working out a patch if it's a feature you would accept, although I'm not familiar with the codebase...

Cheers,

Álex

**Comment by Jc2k** [comment]
If you are getting errors it might be worth pasting them - i've been worried that all the recent changes in pytest might have entirely bricked the tricks `pytest-docker-tools` is using...

I can't see why `fileobj` wouldn't work, other than a docstring that references `path`. As a first step might be worth removing the {path} here and seeing if that helps:

https://github.com/Jc2k/pytest-docker-tools/blob/master/pytest_docker_tools/factories/build.py#L8

I can't remember what that is for. Better output somewhere?

**Comment by alexpdp7** [comment]
Yes, I tried that. There's another "cosmetic" issue:

```
sys.stdout.write(f'Building {kwargs["path"]}')
pytest_docker_tools/factories/build.py
```

, but there are further issues because I think the built image doesn't have a name and thus it cannot be found, so I think there's "non-cosmetic" fixes to be done to address this use case.

I don't have a lot of time for this right now, but I can try to address this at some point (this is for a personal "crazy" side-project. I want to do some uncommon testing and I stumbled with this library, which is exactly what I needed. So getting this done is not a priority for me, but this is a cool library and I wouldn't mind hacking a bit on it).

**Comment by Jc2k** [comment]
It's quite useful :) I have some integration tests that fire up an events broker and a minio instance per test. I think i even had it working with xdist at one point but my memory might be playing tricks on me. But i've not had time to play with it recently, so it would be fantastic to have more eyes on it!

Very happy to take a PR to make this work.

One think to think about - i can't remember if a StringIO can be read multiple times without a `seek(0)`. We might need a hook to reset it between invocations. This won't manifest in the common case because the default scope is session iirc. But if someone is doing something creative that involves more frequent builds i'm guessing it could.

One thing of note, you don't need to pass `build` into `image`. `image` is only to deref a (potentially remote) image reference into a local image object. The retval of build is also an image. E.g. if you get rid of the 2 cosmetic uses of path this works:

```
import io

import pytest_docker_tools as pdt

dockerfile = io.BytesIO(b"""
FROM alpine:3.12
RUN apk --no-cache add python3
CMD ["tail", "-f", "/dev/null"]
""")

image = pdt.build(fileobj=dockerfile)
container = pdt.container(image='{image.id}')


def test_my_dockerfile(container):
    print("it worketh")


def test_my_dockerfile_2(container):
    print("it worketh more")
```

```
python -m pytest tests.py
```

with this set of requirements.txt

```
attrs==19.3.0
certifi==2020.6.20
chardet==3.0.4
docker==4.3.0
idna==2.10
importlib-metadata==1.7.0
iniconfig==1.0.1
more-itertools==8.4.0
packaging==20.4
pluggy==0.13.1
py==1.9.0
pyparsing==2.4.7
pytest==6.0.1
pytest-docker-tools==0.2.2
requests==2.24.0
six==1.15.0
toml==0.10.1
urllib3==1.25.10
websocket-client==0.57.0
zipp==3.1.0
```

**Comment by alexpdp7** [comment]
Sorry, I'm dumb *and* I didn't have time to attend this before.

I've submitted https://github.com/Jc2k/pytest-docker-tools/pull/14 , if you wish we can close this and continue the discussion there.

**Comment by Jc2k** [comment]
Haha. I'll close this then!
