### ISSUE TITLE
Expand on network creation documentation

### ISSUE THREAD

**Issue by jmgilman** [Jc2k/pytest-docker-tools#40]
The README gives the following example:

```
from pytest_docker_tools import network

frontend_network = network()
```

It mentions that the `network()` factory accepts all arguments that are valid for the underlying docker API package. Following this logic, I tried this:

```
import redis
import pytest
from pytest_docker_tools import build, container, fetch, network

test_network = network(name="test_network")

redis_image = fetch(repository="redis:latest")
redis_cont = container(
    image="{redis_image.id}",
    name="redis",
    ports={"6379/tcp": None},
    network="test_network",
)

@pytest.fixture
def my_fixture(redis_cont):
  pass
```

The problem is that the network never gets created, presumably because no fixture ever explicitly required it. The following resolves the issue:

```
@pytest.fixture
def my_fixture(redis_cont, test_network):
  pass
```

The unfortunate side effect is the presence of an unused fixture. This leaves me with the following:

1. Is this the correct way to declare such a dependency? 
2. If so, the network section should be updated with a better example. While this behavior may be clear to a veteran using this package, for someone new to it (like myself) it was very confusing. 

All in all, it's a great package and the documentation is excellent, this is the only area that I got really stuck on.

**Comment by Jc2k** [comment]
So the "trick" that makes this package work is using the python format strings to get a list of other fixtures to depend on. They aren't just variable expansions, they are how pytest-docker-tools knows which fixtures are related to one another and what the proper order is.

So the reason the `redis_image` runs is because `redis_cont` depends on it, because of the `"{redis_image.id}"`. 

Your example is very nearly there, you just need to make `redis_cont` actually depend on the test network. There is this example in the README:

```
from pytest_docker_tools import container, fetch, network

redis_image = fetch(repository='redis:latest')
backend_network = network()

redis = container(
  image='{redis_image.id}',
  network='{backend_network.name}',
)
```

The variable expansion is partly to get the autogenerated name, but its partly to set up the dependencies between the fixtures. So you can do:

```
from pytest_docker_tools import container, fetch, network

redis_image = fetch(repository='redis:latest')
backend_network = network(name="test_network")

redis = container(
  image='{redis_image.id}',
  network='{backend_network.name}',
)
```

And it will work just fine (in theory, if not its a bug!)

That example could do with being duplicated into the network section, and probably needs some more explicit explanation of the dependency capture. Re-reading I realise it's only hinted at.

My head is pretty far out of this package at the moment, real life, work life and other open source commitments, etc. A lot of this package has been paged to swap. So if you wanted to make a doc improvement suggestion PR that would be really appreciated. Otherwise i'll put this on my back back log! 😢

**Comment by jmgilman** [comment]
Ah, the joys of maintaining open-source software. I'm there on a few of my projects as well :) 

Created #41 to address this.
